// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1X9dNMhyFixFqjmepS0iqIZRAGnTv3I',
    appId: '1:566443908608:android:a1a079e4e18964664882e5',
    messagingSenderId: '566443908608',
    projectId: 'crud-65332',
    storageBucket: 'crud-65332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojBMhDD_7CbSJWq1PB0x5z_FCGawifoE',
    appId: '1:566443908608:ios:86be41fda696b0364882e5',
    messagingSenderId: '566443908608',
    projectId: 'crud-65332',
    storageBucket: 'crud-65332.appspot.com',
    iosClientId: '566443908608-5u3ldvdr427pi0d9g9t43qmhnsf86pl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOperation',
  );
}
